apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-service
  labels:
    app: hash-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash-service
  template:
    metadata:
      labels:
        app: hash-service
    spec:
      containers:
        - name: hash-service
          # This will be replaced by the actual ACR login server during deployment
          image: ${ACR_LOGIN_SERVER}/hash-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
